package metier.entities;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livre generated by hbm2java
 */
@Entity
@Table(name = "livre", catalog = "biblio")
public class Livre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int isbn;
	private String titre;
	private String langue;
	private Integer nbrpages;
	private String resume;
	private Long anneesortie;
	private String auteur;
	private Date dateenreg;
	private Integer nbrexemplaire;
	private String affiche;
	//private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Livre() {
	}

	public Livre(int isbn) {
		this.isbn = isbn;
	}

	public Livre(int isbn, String titre, String langue, Integer nbrpages, String resume, Long anneesortie,
			String auteur, Date dateenreg, Integer nbrexemplaire, String affiche,
			Set<Utilisateur> utilisateurs) {
		this.isbn = isbn;
		this.titre = titre;
		this.langue = langue;
		this.nbrpages = nbrpages;
		this.resume = resume;
		this.anneesortie = anneesortie;
		this.auteur = auteur;
		this.dateenreg = dateenreg;
		this.nbrexemplaire = nbrexemplaire;
		this.affiche = affiche;
	//	this.emprunts = emprunts;
		this.utilisateurs = utilisateurs;
	}

	@Id

	@Column(name = "ISBN", unique = true, nullable = false)
	public int getIsbn() {
		return this.isbn;
	}

	public void setIsbn(int isbn) {
		this.isbn = isbn;
	}

	@Column(name = "TITRE", length = 30)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "LANGUE", length = 30)
	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	@Column(name = "NBRPAGES")
	public Integer getNbrpages() {
		return this.nbrpages;
	}

	public void setNbrpages(Integer nbrpages) {
		this.nbrpages = nbrpages;
	}

	@Column(name = "RESUME", length = 65535)
	public String getResume() {
		return this.resume;
	}

	public void setResume(String resume) {
		this.resume = resume;
	}

	@Column(name = "ANNEESORTIE")
	public Long getAnneesortie() {
		return this.anneesortie;
	}

	public void setAnneesortie(Long anneesortie) {
		this.anneesortie = anneesortie;
	}

	@Column(name = "AUTEUR", length = 80)
	public String getAuteur() {
		return this.auteur;
	}

	public void setAuteur(String auteur) {
		this.auteur = auteur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEENREG", length = 10)
	public Date getDateenreg() {
		return this.dateenreg;
	}

	public void setDateenreg(Date dateenreg) {
		this.dateenreg = dateenreg;
	}

	@Column(name = "NBREXEMPLAIRE")
	public Integer getNbrexemplaire() {
		return this.nbrexemplaire;
	}

	public void setNbrexemplaire(Integer nbrexemplaire) {
		this.nbrexemplaire = nbrexemplaire;
	}

	@Column(name = "AFFICHE", length = 80)
	public String getAffiche() {
		return this.affiche;
	}

	public void setAffiche(String affiche) {
		this.affiche = affiche;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "livre")
	public Set<Emprunt> getEmprunts() {
		return this.emprunts;
	}

	public void setEmprunts(Set<Emprunt> emprunts) {
		this.emprunts = emprunts;
	}
*/
	/*@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "reservation", catalog = "biblio", joinColumns = {
			@JoinColumn(name = "ISBN", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CODE", nullable = false, updatable = false) })
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}
*/
}
