package metier.entities;
// Generated 12 janv. 2016 02:22:22 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmpruntId generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "biblio")
public class Reservation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	private int isbn;
	private int code;

	public Reservation() {
	}

	public Reservation(int isbn, int code) {
		this.isbn = isbn;
		this.code = code;
	}
	@Id
	@Column(name = "ISBN", nullable = false)
	public int getIsbn() {
		return this.isbn;
	}

	public void setIsbn(int isbn) {
		this.isbn = isbn;
	}

	@Column(name = "CODE", nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Reservation))
			return false;
		Reservation castOther = (Reservation) other;

		return (this.getIsbn() == castOther.getIsbn()) && (this.getCode() == castOther.getCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIsbn();
		result = 37 * result + this.getCode();
		return result;
	}

}
