package metier.entities;
// Generated 12 janv. 2016 02:22:22 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "biblio")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int code;
	public String nom;
	public String prenom;
	public String login;
	public String password;
	private String email;
	/*private Set<Emprunt> emprunts = new HashSet<Emprunt>(0);
	private Set<Livre> livres = new HashSet<Livre>(0);*/

	public Utilisateur() {
	}

	/*public Utilisateur(int code) {
		this.code = code;
	}
*/
	public Utilisateur(/*int code, */String nom, String prenom, String login, String password, String email) {
		//this.code = code;
		super();
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.email = email;
		
	}

	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "CODE", unique = true, nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@Column(name = "NOM", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "LOGIN", length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Emprunt> getEmprunts() {
		return this.emprunts;
	}*/

	/*public void setEmprunts(Set<Emprunt> emprunts) {
		this.emprunts = emprunts;
	}
*/
	/*@ManyToMany(fetch = FetchType.LAZY, mappedBy = "utilisateurs")
	public Set<Livre> getLivres() {
		return this.livres;
	}*/

	/*public void setLivres(Set<Livre> livres) {
		this.livres = livres;
	}*/

}
